services:
    PhpCsFixer\Fixer\ArrayNotation\ArraySyntaxFixer:
        syntax: short
    PhpCsFixer\Fixer\ArrayNotation\WhitespaceAfterCommaInArrayFixer: ~
    PhpCsFixer\Fixer\ArrayNotation\NoWhitespaceBeforeCommaInArrayFixer: ~
    PhpCsFixer\Fixer\ArrayNotation\TrailingCommaInMultilineArrayFixer: ~

    PhpCsFixer\Fixer\CastNotation\CastSpacesFixer:
        space: none

    PhpCsFixer\Fixer\Comment\MultilineCommentOpeningClosingFixer: ~

    PhpCsFixer\Fixer\FunctionNotation\FunctionTypehintSpaceFixer: ~
    PhpCsFixer\Fixer\FunctionNotation\ReturnTypeDeclarationFixer:
        space_before: none

    PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer: ~
    PhpCsFixer\Fixer\Operator\ConcatSpaceFixer:
        spacing: none
    PhpCsFixer\Fixer\Operator\ObjectOperatorWithoutWhitespaceFixer: ~
    PhpCsFixer\Fixer\Operator\TernaryOperatorSpacesFixer: ~
    PhpCsFixer\Fixer\Operator\UnaryOperatorSpacesFixer: ~

    PhpCsFixer\Fixer\Phpdoc\NoEmptyPhpdocFixer: ~
    PhpCsFixer\Fixer\Phpdoc\PhpdocIndentFixer: ~

    PhpCsFixer\Fixer\Semicolon\NoSinglelineWhitespaceBeforeSemicolonsFixer: ~
    PhpCsFixer\Fixer\Semicolon\SemicolonAfterInstructionFixer: ~
    PhpCsFixer\Fixer\Semicolon\SpaceAfterSemicolonFixer: ~

    PhpCsFixer\Fixer\Whitespace\ArrayIndentationFixer: ~
    PhpCsFixer\Fixer\Whitespace\CompactNullableTypehintFixer: ~
    PhpCsFixer\Fixer\Whitespace\MethodChainingIndentationFixer: ~
    PhpCsFixer\Fixer\Whitespace\NoSpacesAroundOffsetFixer: ~
    PhpCsFixer\Fixer\Whitespace\NoWhitespaceInBlankLineFixer: ~


    SlevomatCodingStandard\Sniffs\Classes\ModernClassNameReferenceSniff: ~
    SlevomatCodingStandard\Sniffs\Operators\DisallowEqualOperatorsSniff: ~
    SlevomatCodingStandard\Sniffs\Namespaces\UseDoesNotStartWithBackslashSniff: ~
    SlevomatCodingStandard\Sniffs\Namespaces\UselessAliasSniff: ~

parameters:
    exclude_files:
        - 'vendor/*'
        - '*/cache/*'

    skip:
        PhpCsFixer\Fixer\Import\NoUnusedImportsFixer: ~
        SlevomatCodingStandard\Sniffs\Variables\UselessVariableSniff.UselessVariable: ~
        PhpCsFixer\Fixer\ReturnNotation\ReturnAssignmentFixer: ~
